apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DATABASE_ID: {{ .Values.app.databaseId }}
  NOTION_API_TOKEN: {{ .Values.app.notionApiToken }}
  CONTENT_DIR: {{ .Values.app.mount_path }}