apiVersion: v1
kind: Service
metadata:
  name: {{ include "clearstatus.fullname" . }}
  labels:
    {{- include "clearstatus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: backend
    - port: 80
      targetPort: 1313
      protocol: TCP
      name: http
  selector:
    {{- include "clearstatus.selectorLabels" . | nindent 4 }}
